package SnmpProyect;
import com.ireasoning.protocol.snmp.*;
public class OIDTree
{
    private static OIDTreeNode _root = null;
    
    public static void resetTree()
    {
        _root = null;
    }
    
    public static OIDTreeNode getTree()
    {
        if(_root != null) return _root;
        OIDTreeNode node_NK_MIB_0 = new OIDTreeNode("");
        node_NK_MIB_0.setMibNodeName("NK_MIB");
        OIDTreeNode node_iso_1 = (OIDTreeNode) node_NK_MIB_0.addChild(".1");
        node_iso_1.setMibNodeName("Iso");
        OIDTreeNode node_org_2 = (OIDTreeNode) node_iso_1.addChild(".1.3");
        node_org_2.setMibNodeName("Org");
        OIDTreeNode node_dod_3 = (OIDTreeNode) node_org_2.addChild(".1.3.6");
        node_dod_3.setMibNodeName("Dod");
        OIDTreeNode node_internet_4 = (OIDTreeNode) node_dod_3.addChild(".1.3.6.1");
        node_internet_4.setMibNodeName("Internet");
        OIDTreeNode node_private_5 = (OIDTreeNode) node_internet_4.addChild(".1.3.6.1.4");
        node_private_5.setMibNodeName("Private");
        OIDTreeNode node_enterprises_6 = (OIDTreeNode) node_private_5.addChild(".1.3.6.1.4.1");
        node_enterprises_6.setMibNodeName("Enterprises");
        OIDTreeNode node_itUniovi_7 = (OIDTreeNode) node_enterprises_6.addChild(".1.3.6.1.4.1.47454");
        node_itUniovi_7.setMibNodeName("ItUniovi");
        OIDTreeNode node_itObjetos_8 = (OIDTreeNode) node_itUniovi_7.addChild(".1.3.6.1.4.1.47454.1");
        node_itObjetos_8.setMibNodeName("ItObjetos");
        OIDTreeNode node_itObjetosConfig_9 = (OIDTreeNode) node_itObjetos_8.addChild(".1.3.6.1.4.1.47454.1.1");
        node_itObjetosConfig_9.setMibNodeName("ItObjetosConfig");
        node_itObjetosConfig_9.setGroupNode(true);
        OIDTreeNode node_rootFolder_10 = (OIDTreeNode) node_itObjetosConfig_9.addChild(".1.3.6.1.4.1.47454.1.1.1.0");
        node_rootFolder_10.setMibNodeName("RootFolder");
        node_rootFolder_10.setScalarNode(true);
        node_rootFolder_10.setRealSyntaxType( (byte) 1);
        node_rootFolder_10.setObjectName("iReasoning:name=ItObjetosConfigGroup,noPdu=true");
        node_rootFolder_10.setAccess(3);
        OIDTreeNode node_itDeleteFiles_11 = (OIDTreeNode) node_itObjetosConfig_9.addChild(".1.3.6.1.4.1.47454.1.1.2.0");
        node_itDeleteFiles_11.setMibNodeName("ItDeleteFiles");
        node_itDeleteFiles_11.setScalarNode(true);
        node_itDeleteFiles_11.setRealSyntaxType( (byte) 2);
        node_itDeleteFiles_11.setObjectName("iReasoning:name=ItObjetosConfigGroup,noPdu=true");
        node_itDeleteFiles_11.setAccess(3);
        OIDTreeNode node_itTestAndIncr_12 = (OIDTreeNode) node_itObjetosConfig_9.addChild(".1.3.6.1.4.1.47454.1.1.3.0");
        node_itTestAndIncr_12.setMibNodeName("ItTestAndIncr");
        node_itTestAndIncr_12.setScalarNode(true);
        node_itTestAndIncr_12.setRealSyntaxType( (byte) 2);
        node_itTestAndIncr_12.setObjectName("iReasoning:name=ItObjetosConfigGroup,noPdu=true");
        node_itTestAndIncr_12.setAccess(3);
        OIDTreeNode node_itGravityLevel_13 = (OIDTreeNode) node_itObjetosConfig_9.addChild(".1.3.6.1.4.1.47454.1.1.4.0");
        node_itGravityLevel_13.setMibNodeName("ItGravityLevel");
        node_itGravityLevel_13.setScalarNode(true);
        node_itGravityLevel_13.setRealSyntaxType( (byte) 2);
        node_itGravityLevel_13.setObjectName("iReasoning:name=ItObjetosConfigGroup,noPdu=true");
        node_itGravityLevel_13.setAccess(1);
        OIDTreeNode node_itUmbralFiles_14 = (OIDTreeNode) node_itObjetosConfig_9.addChild(".1.3.6.1.4.1.47454.1.1.5.0");
        node_itUmbralFiles_14.setMibNodeName("ItUmbralFiles");
        node_itUmbralFiles_14.setScalarNode(true);
        node_itUmbralFiles_14.setRealSyntaxType( (byte) 2);
        node_itUmbralFiles_14.setObjectName("iReasoning:name=ItObjetosConfigGroup,noPdu=true");
        node_itUmbralFiles_14.setAccess(3);
        OIDTreeNode node_itActivarEvents_15 = (OIDTreeNode) node_itObjetosConfig_9.addChild(".1.3.6.1.4.1.47454.1.1.6.0");
        node_itActivarEvents_15.setMibNodeName("ItActivarEvents");
        node_itActivarEvents_15.setScalarNode(true);
        node_itActivarEvents_15.setRealSyntaxType( (byte) 2);
        node_itActivarEvents_15.setObjectName("iReasoning:name=ItObjetosConfigGroup,noPdu=true");
        node_itActivarEvents_15.setAccess(3);
        OIDTreeNode node_itObjetosInfo_16 = (OIDTreeNode) node_itObjetos_8.addChild(".1.3.6.1.4.1.47454.1.2");
        node_itObjetosInfo_16.setMibNodeName("ItObjetosInfo");
        node_itObjetosInfo_16.setGroupNode(true);
        OIDTreeNode node_itDirRequests_17 = (OIDTreeNode) node_itObjetosInfo_16.addChild(".1.3.6.1.4.1.47454.1.2.1.0");
        node_itDirRequests_17.setMibNodeName("ItDirRequests");
        node_itDirRequests_17.setScalarNode(true);
        node_itDirRequests_17.setRealSyntaxType( (byte) 2);
        node_itDirRequests_17.setObjectName("iReasoning:name=ItObjetosInfoGroup,noPdu=true");
        node_itDirRequests_17.setAccess(2);
        OIDTreeNode node_itFrecSondeo_18 = (OIDTreeNode) node_itObjetosInfo_16.addChild(".1.3.6.1.4.1.47454.1.2.2.0");
        node_itFrecSondeo_18.setMibNodeName("ItFrecSondeo");
        node_itFrecSondeo_18.setScalarNode(true);
        node_itFrecSondeo_18.setRealSyntaxType( (byte) 2);
        node_itFrecSondeo_18.setObjectName("iReasoning:name=ItObjetosInfoGroup,noPdu=true");
        node_itFrecSondeo_18.setAccess(3);
        OIDTreeNode node_itObjetosState_19 = (OIDTreeNode) node_itObjetos_8.addChild(".1.3.6.1.4.1.47454.1.3");
        node_itObjetosState_19.setMibNodeName("ItObjetosState");
        node_itObjetosState_19.setGroupNode(true);
        OIDTreeNode node_itNumFiles_20 = (OIDTreeNode) node_itObjetosState_19.addChild(".1.3.6.1.4.1.47454.1.3.1.0");
        node_itNumFiles_20.setMibNodeName("ItNumFiles");
        node_itNumFiles_20.setScalarNode(true);
        node_itNumFiles_20.setRealSyntaxType( (byte) 2);
        node_itNumFiles_20.setObjectName("iReasoning:name=ItObjetosStateGroup,noPdu=true");
        node_itNumFiles_20.setAccess(2);
        OIDTreeNode node_itConformance_21 = (OIDTreeNode) node_itUniovi_7.addChild(".1.3.6.1.4.1.47454.2");
        node_itConformance_21.setMibNodeName("ItConformance");
        OIDTreeNode node_itCompliance_22 = (OIDTreeNode) node_itConformance_21.addChild(".1.3.6.1.4.1.47454.2.1");
        node_itCompliance_22.setMibNodeName("ItCompliance");
        node_itCompliance_22.setGroupNode(true);
        OIDTreeNode node_itCompliances_23 = (OIDTreeNode) node_itCompliance_22.addChild(".1.3.6.1.4.1.47454.2.1.1");
        node_itCompliances_23.setMibNodeName("ItCompliances");
        OIDTreeNode node_itGrupos_24 = (OIDTreeNode) node_itConformance_21.addChild(".1.3.6.1.4.1.47454.2.2");
        node_itGrupos_24.setMibNodeName("ItGrupos");
        node_itGrupos_24.setGroupNode(true);
        OIDTreeNode node_grpObjetos_25 = (OIDTreeNode) node_itGrupos_24.addChild(".1.3.6.1.4.1.47454.2.2.1");
        node_grpObjetos_25.setMibNodeName("GrpObjetos");
        OIDTreeNode node_grpEventos_26 = (OIDTreeNode) node_itGrupos_24.addChild(".1.3.6.1.4.1.47454.2.2.2");
        node_grpEventos_26.setMibNodeName("GrpEventos");
        OIDTreeNode node_itEvents_27 = (OIDTreeNode) node_itUniovi_7.addChild(".1.3.6.1.4.1.47454.3");
        node_itEvents_27.setMibNodeName("ItEvents");
        OIDTreeNode node_itEventList_28 = (OIDTreeNode) node_itEvents_27.addChild(".1.3.6.1.4.1.47454.3.0");
        node_itEventList_28.setMibNodeName("ItEventList");
        node_itEventList_28.setGroupNode(true);
        OIDTreeNode node_itEventGravity_29 = (OIDTreeNode) node_itEventList_28.addChild(".1.3.6.1.4.1.47454.3.0.1");
        node_itEventGravity_29.setMibNodeName("ItEventGravity");
        OIDTreeNode node_itFilesChangeEvent_30 = (OIDTreeNode) node_itEventList_28.addChild(".1.3.6.1.4.1.47454.3.0.2");
        node_itFilesChangeEvent_30.setMibNodeName("ItFilesChangeEvent");
        OIDTreeNode node_itDeleteFilesEvent_31 = (OIDTreeNode) node_itEventList_28.addChild(".1.3.6.1.4.1.47454.3.0.3");
        node_itDeleteFilesEvent_31.setMibNodeName("ItDeleteFilesEvent");
        OIDTreeNode node_itEventUmFich_32 = (OIDTreeNode) node_itEventList_28.addChild(".1.3.6.1.4.1.47454.3.0.4");
        node_itEventUmFich_32.setMibNodeName("ItEventUmFich");
        _root = node_NK_MIB_0 ;
        return node_NK_MIB_0;
    }
    
    public static final String ITOBJETOS = ".1.3.6.1.4.1.47454.1";
    public static final String ITEVENTS = ".1.3.6.1.4.1.47454.3";
    public static final String ISO = ".1";
    public static final String ITCONFORMANCE = ".1.3.6.1.4.1.47454.2";
    public static final String ITDIRREQUESTS = ".1.3.6.1.4.1.47454.1.2.1.0";
    public static final String ITFRECSONDEO = ".1.3.6.1.4.1.47454.1.2.2.0";
    public static final String ENTERPRISES = ".1.3.6.1.4.1";
    public static final String ITNUMFILES = ".1.3.6.1.4.1.47454.1.3.1.0";
    public static final String DOD = ".1.3.6";
    public static final String ORG = ".1.3";
    public static final String ITEVENTUMFICH = ".1.3.6.1.4.1.47454.3.0.4";
    public static final String ITDELETEFILESEVENT = ".1.3.6.1.4.1.47454.3.0.3";
    public static final String ITFILESCHANGEEVENT = ".1.3.6.1.4.1.47454.3.0.2";
    public static final String ITEVENTGRAVITY = ".1.3.6.1.4.1.47454.3.0.1";
    public static final String GRPOBJETOS = ".1.3.6.1.4.1.47454.2.2.1";
    public static final String ITCOMPLIANCES = ".1.3.6.1.4.1.47454.2.1.1";
    public static final String GRPEVENTOS = ".1.3.6.1.4.1.47454.2.2.2";
    public static final String ITACTIVAREVENTS = ".1.3.6.1.4.1.47454.1.1.6.0";
    public static final String ITGRAVITYLEVEL = ".1.3.6.1.4.1.47454.1.1.4.0";
    public static final String ITUMBRALFILES = ".1.3.6.1.4.1.47454.1.1.5.0";
    public static final String ITDELETEFILES = ".1.3.6.1.4.1.47454.1.1.2.0";
    public static final String PRIVATE = ".1.3.6.1.4";
    public static final String ITUNIOVI = ".1.3.6.1.4.1.47454";
    public static final String ITTESTANDINCR = ".1.3.6.1.4.1.47454.1.1.3.0";
    public static final String ROOTFOLDER = ".1.3.6.1.4.1.47454.1.1.1.0";
    public static final String INTERNET = ".1.3.6.1";
    public static final String ITOBJETOSSTATE = ".1.3.6.1.4.1.47454.1.3";
    public static final String ITGRUPOS = ".1.3.6.1.4.1.47454.2.2";
    public static final String ITOBJETOSINFO = ".1.3.6.1.4.1.47454.1.2";
    public static final String ITCOMPLIANCE = ".1.3.6.1.4.1.47454.2.1";
    public static final String ITEVENTLIST = ".1.3.6.1.4.1.47454.3.0";
    public static final String ITOBJETOSCONFIG = ".1.3.6.1.4.1.47454.1.1";
}
